## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("../Resources/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
app_df = application_df.drop(columns = ["EIN", "NAME"])
app_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [3]:
# Determine the number of unique values in each column.
app_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
app_type = app_df["APPLICATION_TYPE"].value_counts()
app_type

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T14        3
T25        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_type[app_type<100].index)
application_types_to_replace

# Replace in dataframe
for app in application_types_to_replace:
    app_df['APPLICATION_TYPE'] = app_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
app_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
Other      120
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
class_type = app_df["CLASSIFICATION"].value_counts()
class_type

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C1900        1
C1236        1
C1245        1
C2190        1
C1370        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_value = class_type[class_type>1]
class_value

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C2300       32
C7200       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C0           3
C2710        3
C1234        2
C1256        2
C1267        2
C1246        2
C3200        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(class_type[class_type<115].index)

# Replace in dataframe
for cls in classifications_to_replace:
    app_df['CLASSIFICATION'] = app_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
app_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other      887
C7000      777
C1700      287
C4000      194
C5000      116
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
new_app_df = pd.get_dummies(app_df)
new_app_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [16]:
# Split our preprocessed data into our features and target arrays
X = new_app_df.drop(columns=["IS_SUCCESSFUL"],axis=1)
y = new_app_df["IS_SUCCESSFUL"]


# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [17]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [25]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn_model = tf.keras.models.Sequential()

# First hidden layer
nn_model.add(tf.keras.layers.Dense(units=50, activation="relu", input_dim=len(X_train_scaled[0])))

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=30, activation="relu"))

# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_12 (Dense)            (None, 50)                2450

 dense_13 (Dense)            (None, 30)                1530

 dense_14 (Dense)            (None, 1)                 31

=================================================================
Total params: 4,011
Trainable params: 4,011
Non-trainable params: 0
_________________________________________________________________

In [26]:
# Compile the model
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train the model
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=200)

Epoch 1/200
804/804 [==============================] - 1s 971us/step - loss: 0.5702 - accuracy: 0.7208
Epoch 2/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5533 - accuracy: 0.7295
Epoch 3/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5501 - accuracy: 0.7307
Epoch 4/200
804/804 [==============================] - 1s 993us/step - loss: 0.5486 - accuracy: 0.7313
Epoch 5/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5475 - accuracy: 0.7319
Epoch 6/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5467 - accuracy: 0.7315
Epoch 7/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5457 - accuracy: 0.7329
Epoch 8/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5450 - accuracy: 0.7337
Epoch 9/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5441 - accuracy: 0.7329
Epoch 10/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5440 - accuracy: 0.7339
Epoch 11/200
804/804 [==============================] - 1s 971us/step - loss: 0.5437 - accuracy: 0.7344
Epoch 12/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5429 - accuracy: 0.7339
Epoch 13/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7345
Epoch 14/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5424 - accuracy: 0.7346
Epoch 15/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5418 - accuracy: 0.7343
Epoch 16/200
804/804 [==============================] - 1s 981us/step - loss: 0.5415 - accuracy: 0.7357
Epoch 17/200
804/804 [==============================] - 1s 991us/step - loss: 0.5416 - accuracy: 0.7353
Epoch 18/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5412 - accuracy: 0.7355
Epoch 19/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5409 - accuracy: 0.7365
Epoch 20/200
804/804 [==============================] - 1s 981us/step - loss: 0.5409 - accuracy: 0.7357
Epoch 21/200
804/804 [==============================] - 1s 989us/step - loss: 0.5407 - accuracy: 0.7348
Epoch 22/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5402 - accuracy: 0.7381
Epoch 23/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5402 - accuracy: 0.7369
Epoch 24/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5397 - accuracy: 0.7373
Epoch 25/200
804/804 [==============================] - 1s 977us/step - loss: 0.5395 - accuracy: 0.7364
Epoch 26/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5393 - accuracy: 0.7375
Epoch 27/200
804/804 [==============================] - 1s 936us/step - loss: 0.5391 - accuracy: 0.7369
Epoch 28/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5393 - accuracy: 0.7370
Epoch 29/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5390 - accuracy: 0.7380
Epoch 30/200
804/804 [==============================] - 1s 988us/step - loss: 0.5390 - accuracy: 0.7380
Epoch 31/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5389 - accuracy: 0.7376
Epoch 32/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5383 - accuracy: 0.7384
Epoch 33/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5385 - accuracy: 0.7376
Epoch 34/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5384 - accuracy: 0.7387
Epoch 35/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5377 - accuracy: 0.7385
Epoch 36/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5377 - accuracy: 0.7381
Epoch 37/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5375 - accuracy: 0.7391
Epoch 38/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5378 - accuracy: 0.7379
Epoch 39/200
804/804 [==============================] - 1s 996us/step - loss: 0.5380 - accuracy: 0.7375
Epoch 40/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5374 - accuracy: 0.7392
Epoch 41/200
804/804 [==============================] - 1s 962us/step - loss: 0.5374 - accuracy: 0.7371
Epoch 42/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5370 - accuracy: 0.7374
Epoch 43/200
804/804 [==============================] - 1s 988us/step - loss: 0.5370 - accuracy: 0.7387
Epoch 44/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5369 - accuracy: 0.7388
Epoch 45/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5367 - accuracy: 0.7399
Epoch 46/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5370 - accuracy: 0.7388
Epoch 47/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5369 - accuracy: 0.7378
Epoch 48/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5368 - accuracy: 0.7388
Epoch 49/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5366 - accuracy: 0.7385
Epoch 50/200
804/804 [==============================] - 1s 982us/step - loss: 0.5362 - accuracy: 0.7389
Epoch 51/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5362 - accuracy: 0.7400
Epoch 52/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5362 - accuracy: 0.7401
Epoch 53/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5361 - accuracy: 0.7390
Epoch 54/200
804/804 [==============================] - 1s 959us/step - loss: 0.5359 - accuracy: 0.7397
Epoch 55/200
804/804 [==============================] - 1s 972us/step - loss: 0.5359 - accuracy: 0.7392
Epoch 56/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5356 - accuracy: 0.7386
Epoch 57/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5355 - accuracy: 0.7395
Epoch 58/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5356 - accuracy: 0.7388
Epoch 59/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5358 - accuracy: 0.7404
Epoch 60/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5356 - accuracy: 0.7407
Epoch 61/200
804/804 [==============================] - 1s 985us/step - loss: 0.5354 - accuracy: 0.7399
Epoch 62/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5352 - accuracy: 0.7396
Epoch 63/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5352 - accuracy: 0.7393
Epoch 64/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5353 - accuracy: 0.7394
Epoch 65/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5348 - accuracy: 0.7394
Epoch 66/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5349 - accuracy: 0.7394
Epoch 67/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5349 - accuracy: 0.7411
Epoch 68/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5346 - accuracy: 0.7406
Epoch 69/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5347 - accuracy: 0.7404
Epoch 70/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5343 - accuracy: 0.7397
Epoch 71/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5345 - accuracy: 0.7411
Epoch 72/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5341 - accuracy: 0.7401
Epoch 73/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5351 - accuracy: 0.7410
Epoch 74/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5348 - accuracy: 0.7404
Epoch 75/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5341 - accuracy: 0.7401
Epoch 76/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5343 - accuracy: 0.7405
Epoch 77/200
804/804 [==============================] - 1s 952us/step - loss: 0.5342 - accuracy: 0.7401
Epoch 78/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5340 - accuracy: 0.7403
Epoch 79/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5342 - accuracy: 0.7409
Epoch 80/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5339 - accuracy: 0.7401
Epoch 81/200

804/804 [==============================] - 1s 1ms/step - loss: 0.5344 - accuracy: 0.7404
Epoch 82/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5343 - accuracy: 0.7406
Epoch 83/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5337 - accuracy: 0.7410
Epoch 84/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5336 - accuracy: 0.7405
Epoch 85/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5340 - accuracy: 0.7399
Epoch 86/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5335 - accuracy: 0.7408
Epoch 87/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5339 - accuracy: 0.7402
Epoch 88/200
804/804 [==============================] - 1s 876us/step - loss: 0.5335 - accuracy: 0.7405
Epoch 89/200
804/804 [==============================] - 1s 985us/step - loss: 0.5336 - accuracy: 0.7400
Epoch 90/200
804/804 [==============================] - 1s 829us/step - loss: 0.5337 - accuracy: 0.7397
Epoch 91/200
804/804 [==============================] - 1s 808us/step - loss: 0.5336 - accuracy: 0.7400
Epoch 92/200
804/804 [==============================] - 1s 777us/step - loss: 0.5334 - accuracy: 0.7387
Epoch 93/200
804/804 [==============================] - 1s 798us/step - loss: 0.5333 - accuracy: 0.7406
Epoch 94/200
804/804 [==============================] - 1s 798us/step - loss: 0.5334 - accuracy: 0.7403
Epoch 95/200
804/804 [==============================] - 1s 770us/step - loss: 0.5337 - accuracy: 0.7411
Epoch 96/200
804/804 [==============================] - 1s 809us/step - loss: 0.5333 - accuracy: 0.7409
Epoch 97/200
804/804 [==============================] - 1s 786us/step - loss: 0.5334 - accuracy: 0.7404
Epoch 98/200
804/804 [==============================] - 1s 768us/step - loss: 0.5333 - accuracy: 0.7407
Epoch 99/200
804/804 [==============================] - 1s 791us/step - loss: 0.5332 - accuracy: 0.7404
Epoch 100/200
804/804 [==============================] - 1s 773us/step - loss: 0.5331 - accuracy: 0.7403
Epoch 101/200
804/804 [==============================] - 1s 787us/step - loss: 0.5331 - accuracy: 0.7399
Epoch 102/200
804/804 [==============================] - 1s 791us/step - loss: 0.5332 - accuracy: 0.7406
Epoch 103/200
804/804 [==============================] - 1s 766us/step - loss: 0.5327 - accuracy: 0.7407
Epoch 104/200
804/804 [==============================] - 1s 773us/step - loss: 0.5331 - accuracy: 0.7403
Epoch 105/200
804/804 [==============================] - 1s 778us/step - loss: 0.5330 - accuracy: 0.7403
Epoch 106/200
804/804 [==============================] - 1s 791us/step - loss: 0.5332 - accuracy: 0.7405
Epoch 107/200
804/804 [==============================] - 1s 921us/step - loss: 0.5329 - accuracy: 0.7411
Epoch 108/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5328 - accuracy: 0.7412
Epoch 109/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5330 - accuracy: 0.7397
Epoch 110/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5330 - accuracy: 0.7411
Epoch 111/200
804/804 [==============================] - 1s 901us/step - loss: 0.5328 - accuracy: 0.7407
Epoch 112/200
804/804 [==============================] - 1s 904us/step - loss: 0.5325 - accuracy: 0.7414
Epoch 113/200
804/804 [==============================] - 1s 959us/step - loss: 0.5326 - accuracy: 0.7413
Epoch 114/200
804/804 [==============================] - 1s 789us/step - loss: 0.5324 - accuracy: 0.7410
Epoch 115/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5327 - accuracy: 0.7406
Epoch 116/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5325 - accuracy: 0.7411
Epoch 117/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5327 - accuracy: 0.7412
Epoch 118/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5325 - accuracy: 0.7404
Epoch 119/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5328 - accuracy: 0.7401
Epoch 120/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5326 - accuracy: 0.7413
Epoch 121/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5327 - accuracy: 0.7410
Epoch 122/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5326 - accuracy: 0.7407
Epoch 123/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5319 - accuracy: 0.7413
Epoch 124/200
804/804 [==============================] - 1s 999us/step - loss: 0.5323 - accuracy: 0.7414
Epoch 125/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5321 - accuracy: 0.7407
Epoch 126/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5323 - accuracy: 0.7414
Epoch 127/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5326 - accuracy: 0.7406
Epoch 128/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5325 - accuracy: 0.7408
Epoch 129/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5322 - accuracy: 0.7408
Epoch 130/200
804/804 [==============================] - 1s 999us/step - loss: 0.5319 - accuracy: 0.7413
Epoch 131/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5321 - accuracy: 0.7403
Epoch 132/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5318 - accuracy: 0.7407
Epoch 133/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5320 - accuracy: 0.7413
Epoch 134/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5320 - accuracy: 0.7411
Epoch 135/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5320 - accuracy: 0.7410
Epoch 136/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5320 - accuracy: 0.7414
Epoch 137/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5318 - accuracy: 0.7414
Epoch 138/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5322 - accuracy: 0.7413
Epoch 139/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5321 - accuracy: 0.7413
Epoch 140/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5315 - accuracy: 0.7411
Epoch 141/200
804/804 [==============================] - 1s 968us/step - loss: 0.5321 - accuracy: 0.7410
Epoch 142/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5317 - accuracy: 0.7413
Epoch 143/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5320 - accuracy: 0.7404
Epoch 144/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5318 - accuracy: 0.7412
Epoch 145/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5314 - accuracy: 0.7412
Epoch 146/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5318 - accuracy: 0.7414
Epoch 147/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5317 - accuracy: 0.7418
Epoch 148/200
804/804 [==============================] - 1s 964us/step - loss: 0.5319 - accuracy: 0.7416
Epoch 149/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5314 - accuracy: 0.7412
Epoch 150/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5316 - accuracy: 0.7412
Epoch 151/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5316 - accuracy: 0.7413
Epoch 152/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5317 - accuracy: 0.7411
Epoch 153/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5316 - accuracy: 0.7417
Epoch 154/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5315 - accuracy: 0.7414
Epoch 155/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5316 - accuracy: 0.7415
Epoch 156/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5317 - accuracy: 0.7405
Epoch 157/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5318 - accuracy: 0.7414
Epoch 158/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5316 - accuracy: 0.7413
Epoch 159/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5313 - accuracy: 0.7421
Epoch 160/200

804/804 [==============================] - 1s 1ms/step - loss: 0.5314 - accuracy: 0.7405
Epoch 161/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5312 - accuracy: 0.7418
Epoch 162/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5314 - accuracy: 0.7416
Epoch 163/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5313 - accuracy: 0.7420
Epoch 164/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5312 - accuracy: 0.7416
Epoch 165/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5312 - accuracy: 0.7418
Epoch 166/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5315 - accuracy: 0.7415
Epoch 167/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5308 - accuracy: 0.7416
Epoch 168/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5311 - accuracy: 0.7414
Epoch 169/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5312 - accuracy: 0.7422
Epoch 170/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5318 - accuracy: 0.7411
Epoch 171/200
804/804 [==============================] - 1s 979us/step - loss: 0.5314 - accuracy: 0.7411
Epoch 172/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5310 - accuracy: 0.7413
Epoch 173/200
804/804 [==============================] - 1s 953us/step - loss: 0.5313 - accuracy: 0.7415
Epoch 174/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5313 - accuracy: 0.7419
Epoch 175/200
804/804 [==============================] - 1s 979us/step - loss: 0.5310 - accuracy: 0.7411
Epoch 176/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5313 - accuracy: 0.7413
Epoch 177/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5310 - accuracy: 0.7423
Epoch 178/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5307 - accuracy: 0.7414
Epoch 179/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5313 - accuracy: 0.7407
Epoch 180/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5311 - accuracy: 0.7405
Epoch 181/200
804/804 [==============================] - 1s 996us/step - loss: 0.5310 - accuracy: 0.7417
Epoch 182/200
804/804 [==============================] - 1s 985us/step - loss: 0.5311 - accuracy: 0.7418
Epoch 183/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5308 - accuracy: 0.7417
Epoch 184/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5309 - accuracy: 0.7413
Epoch 185/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5313 - accuracy: 0.7416
Epoch 186/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5306 - accuracy: 0.7420
Epoch 187/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5309 - accuracy: 0.7418
Epoch 188/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5309 - accuracy: 0.7417
Epoch 189/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5305 - accuracy: 0.7413
Epoch 190/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5313 - accuracy: 0.7412
Epoch 191/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5308 - accuracy: 0.7421
Epoch 192/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5310 - accuracy: 0.7417
Epoch 193/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5310 - accuracy: 0.7421
Epoch 194/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5309 - accuracy: 0.7409
Epoch 195/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5307 - accuracy: 0.7416
Epoch 196/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5310 - accuracy: 0.7416
Epoch 197/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5310 - accuracy: 0.7421
Epoch 198/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5305 - accuracy: 0.7418
Epoch 199/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5307 - accuracy: 0.7421
Epoch 200/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5312 - accuracy: 0.7420

In [28]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5591 - accuracy: 0.7300 - 210ms/epoch - 783us/step
Loss: 0.5590839385986328, Accuracy: 0.7300291657447815

In [29]:
# Export our model to HDF5 file
nn_model.save("My_Model.h5")